feat($properties): update - update 오류 코드와 메시지 처리6
<스프링이 직접 만든 오류 메시지 처리>

- 검증 오류 코드는 다음과 같이 2가지로 나눌 수 있다.
: 개발자가 직접 설정한 오류 코드 rejectValue() 를 직접 호출
: 스프링이 직접 검증 오류에 추가한 경우(주로 타입 정보가 맞지 않음)

- 지금까지 학습한 메시지 코드 전략의 강점을 지금부터 확인해보자.
: price 필드에 문자 "A"를 입력해보자.
: 로그를 확인해보면 BindingResult 에 FieldError 가 담겨있고, 다음과 같은 메시지 코드들이 생성된 것을 확인할 수 있다.
===============================================================================================
codes[typeMismatch.item.price,typeMismatch.price,typeMismatch.java.lang.Integer,typeMismatch]
===============================================================================================

- 다음과 같이 4가지 메시지 코드가 입력되어 있다.
typeMismatch.item.price
typeMismatch.price
typeMismatch.java.lang.Integer
typeMismatch
: 그렇다. 스프링은 타입 오류가 발생하면 typeMismatch 라는 오류 코드를 사용한다.
: 이 오류 코드가 MessageCodesResolver 를 통하면서 4가지 메시지 코드가 생성된 것이다.

- 실행해보자.
: 아직 errors.properties 에 메시지 코드가 없기 때문에 스프링이 생성한 기본 메시지가 출력된다.
===============================================================================================
Failed to convert property value of type java.lang.String to required type
java.lang.Integer for property price; nested exception is
java.lang.NumberFormatException: For input string: "A"
===============================================================================================

- error.properties 에 다음 내용을 추가하자
===============================================================================================
#추가
typeMismatch.java.lang.Integer=숫자를 입력해주세요.
typeMismatch=타입 오류입니다.
===============================================================================================
- 다시 실행해보자
: 결과적으로 소스코드를 하나도 건들지 않고, 원하는 메시지를 단계별로 설정할 수 있다.

- 정리
메시지 코드 생성 전략은 그냥 만들어진 것이 아니다. 조금 뒤에서 Bean Validation을 학습하면 그 진가를 더 확인할 수 있다